// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUa-mxRZcgWZtFdKjDs7lb01eCpJZSQnQ',
    appId: '1:450034906182:web:45c82f87d7d74562010647',
    messagingSenderId: '450034906182',
    projectId: 'chat-app-dc0d3',
    authDomain: 'chat-app-dc0d3.firebaseapp.com',
    storageBucket: 'chat-app-dc0d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZhzk_mjfLd0xJMDJMIX7jRP5gX8J8ctY',
    appId: '1:450034906182:android:83f7da6288c1f553010647',
    messagingSenderId: '450034906182',
    projectId: 'chat-app-dc0d3',
    storageBucket: 'chat-app-dc0d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsdWUUHmA4A5Gkq-dY348DyHRN5Q8stCA',
    appId: '1:450034906182:ios:c8bb3e16b1aef637010647',
    messagingSenderId: '450034906182',
    projectId: 'chat-app-dc0d3',
    storageBucket: 'chat-app-dc0d3.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsdWUUHmA4A5Gkq-dY348DyHRN5Q8stCA',
    appId: '1:450034906182:ios:c8bb3e16b1aef637010647',
    messagingSenderId: '450034906182',
    projectId: 'chat-app-dc0d3',
    storageBucket: 'chat-app-dc0d3.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUa-mxRZcgWZtFdKjDs7lb01eCpJZSQnQ',
    appId: '1:450034906182:web:7636c05324a09e0e010647',
    messagingSenderId: '450034906182',
    projectId: 'chat-app-dc0d3',
    authDomain: 'chat-app-dc0d3.firebaseapp.com',
    storageBucket: 'chat-app-dc0d3.appspot.com',
  );
}
